# -*- coding: utf-8 -*-
"""SalaryAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HL_rU99kHW0DgcoGzwqAMfeAMH-wpEIQ

**1. Install PySpark**
"""

!pip install pyspark

"""**2. Import Libraries**"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import *

import matplotlib.pyplot as plt
import pandas as pd

"""**3. Create Spark Session**"""

spark = SparkSession.builder \
    .appName("SalaryAnalysis") \
    .getOrCreate()

"""**4. Load Dataset**"""

df = spark.read.csv(
    "/content/Salary Data.csv",
    header=True,
    inferSchema=True
)

"""**5. Show Dataset**"""

df.show(5)

"""**6. Print Schema**"""

df.printSchema()

"""**7. Dataset Information**

Number of Rows
"""

print("Rows Count:", df.count())

"""Number of Columns"""

print("Columns Count:", len(df.columns))

"""Column Names"""

print(df.columns)

"""**8. Data Cleaning**

Remove Null Values
"""

df = df.dropna()

"""Remove Duplicate Rows"""

df = df.dropDuplicates()

"""Check Null Values"""

from pyspark.sql.functions import col, isnan, when, count

null_counts = df.select([
    count(when(col(c).isNull(), c)).alias(c)
    for c in df.columns
])

null_counts.show()

"""# 9. Basic Statistics"""

df.describe().show()

"""# Analysis 1: Average Salary"""

from pyspark.sql.functions import avg

avg_salary = df.agg(
    avg("Salary").alias("AverageSalary")
)

avg_salary.show()

"""# Analysis 2: Maximum Salary"""

max_salary = df.agg(
    max("Salary").alias("MaxSalary")
)

max_salary.show()

"""# Analysis 3: Minimum Salary"""

min_salary = df.agg(
    min("Salary").alias("MinSalary")
)

min_salary.show()

"""# Analysis 4: Highest Paid Job Titles"""

top_jobs = df.groupBy("Job Title") \
    .agg(avg("Salary").alias("AverageSalary")) \
    .orderBy("AverageSalary", ascending=False)


top_jobs.show(10)

top_jobs_pd = top_jobs.limit(10).toPandas()

plt.figure(figsize=(12,6))

plt.bar(
    top_jobs_pd["Job Title"],
    top_jobs_pd["AverageSalary"]
)

plt.xticks(rotation=45)

plt.title("Top Highest Paid Jobs")
plt.xlabel("Job Title")
plt.ylabel("Average Salary")

plt.show()

"""# Analysis 5: Salary by Gender"""

gender_salary = df.groupBy("Gender") \
    .agg(avg("Salary").alias("AverageSalary"))


gender_salary.show()

gender_salary_pd = gender_salary.toPandas()

plt.figure(figsize=(6,5))

plt.bar(
    gender_salary_pd["Gender"],
    gender_salary_pd["AverageSalary"]
)

plt.title("Salary by Gender")
plt.xlabel("Gender")
plt.ylabel("Average Salary")

plt.show()

"""# Analysis 6: Salary by Education Level"""

education_salary = df.groupBy("Education Level") \
    .agg(avg("Salary").alias("AverageSalary")) \
    .orderBy("AverageSalary", ascending=False)

education_salary.show()

education_salary_pd = education_salary.toPandas()

plt.figure(figsize=(8,5))

plt.bar(
    education_salary_pd["Education Level"],
    education_salary_pd["AverageSalary"]
)

plt.title("Salary by Education Level")
plt.xlabel("Education")
plt.ylabel("Average Salary")

plt.show()

"""# Analysis 7: Experience vs Salary"""

experience_salary = df.groupBy("Years of Experience") \
    .agg(avg("Salary").alias("AverageSalary")) \
    .orderBy("Years of Experience")

experience_salary.show()

experience_salary_pd = experience_salary.toPandas()

plt.figure(figsize=(10,5))

plt.plot(
    experience_salary_pd["Years of Experience"],
    experience_salary_pd["AverageSalary"],
    marker='o'
)

plt.title("Experience Impact on Salary")
plt.xlabel("Years of Experience")
plt.ylabel("Average Salary")

plt.grid()

plt.show()

"""# Analysis 8: Salary Distribution"""

salary_pd = df.select("Salary").toPandas()

plt.figure(figsize=(10,5))

plt.hist(
    salary_pd["Salary"],
    bins=20
)

plt.title("Salary Distribution")
plt.xlabel("Salary")
plt.ylabel("Frequency")

plt.show()

"""# Analysis 9: Employees Count by Gender"""

gender_count = df.groupBy("Gender") \
    .count()


gender_count.show()

gender_count_pd = gender_count.toPandas()

plt.figure(figsize=(6,6))

plt.pie(
    gender_count_pd["count"],
    labels=gender_count_pd["Gender"],
    autopct='%1.1f%%'
)

plt.title("Employees by Gender")

plt.show()

"""# Analysis 10: Top Experienced Employees"""

top_experience = df.orderBy(
    col("Years of Experience").desc()
)


top_experience.show(10)

"""# Analysis 11: Top Salaries"""

top_salaries = df.orderBy(
    col("Salary").desc()
)


top_salaries.show(10)

"""# Analysis 12: Salary by Age"""

age_salary = df.groupBy("Age") \
    .agg(avg("Salary").alias("AverageSalary")) \
    .orderBy("Age")

age_salary.show()

age_salary_pd = age_salary.toPandas()

plt.figure(figsize=(10,5))

plt.plot(
    age_salary_pd["Age"],
    age_salary_pd["AverageSalary"],
    marker='o'
)

plt.title("Salary by Age")
plt.xlabel("Age")
plt.ylabel("Average Salary")

plt.grid()

plt.show()

"""# Analysis 13: Correlation Between Experience and Salary"""

correlation = df.stat.corr(
    "Years of Experience",
    "Salary"
)

print("Correlation:", correlation)

"""#Analysis 14: Average Salary by Age Group"""

df = df.withColumn(
    "AgeGroup",
    when(col("Age") < 30, "20s")
    .when(col("Age") < 40, "30s")
    .when(col("Age") < 50, "40s")
    .otherwise("50+")
)

age_group_salary = df.groupBy("AgeGroup") \
    .agg(avg("Salary").alias("AverageSalary"))

age_group_salary.show()

age_group_pd = age_group_salary.toPandas()

plt.figure(figsize=(8,5))

plt.bar(
    age_group_pd["AgeGroup"],
    age_group_pd["AverageSalary"]
)

plt.title("Average Salary by Age Group")
plt.xlabel("Age Group")
plt.ylabel("Average Salary")

plt.show()

"""# Analysis 15: Employees Count by Education Level"""

education_count = df.groupBy("Education Level") \
    .count()

education_count.show()

education_count_pd = education_count.toPandas()

plt.figure(figsize=(7,7))

plt.pie(
    education_count_pd["count"],
    labels=education_count_pd["Education Level"],
    autopct='%1.1f%%'
)

plt.title("Employees by Education Level")

plt.show()

"""# KPI Metrics

Total Employees
"""

print("Total Employees:", df.count())

"""Total Job Titles"""

job_titles = df.select("Job Title") \
    .distinct() \
    .count()

print("Total Job Titles:", job_titles)

"""# Average Experience"""

avg_experience = df.agg(
    avg("Years of Experience")
)

avg_experience.show()